function [RptgenML_CReport1] = buildReport
%BUILDREPORT
 
%  Auto-generated by MATLAB on 04-Mar-2015 10:01:15
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('isAutoSaveOnGenerate',true,...
'Format','pdf-fop',...
'Stylesheet','!fo-NoOptions');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('SectionTitle','Two Generators');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph('ParaTitle','');
rptgen_cfr_text1 = rptgen.cfr_text('Content','Parameters:');
set(rptgen_cfr_paragraph1,'ParaTextComp',rptgen_cfr_text1);
setParent(rptgen_cfr_paragraph1,RptgenML_CReport1);
 
% Create rptgen_lo.clo_for
rptgen_lo_clo_for1 = rptgen_lo.clo_for('EndNumber','2');
setParent(rptgen_lo_clo_for1,rptgen_cfr_paragraph1);
 
% Create rptgen.cml_eval
rptgen_cml_eval1 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'EvalString',['clear all',sprintf('\n'),'close all',sprintf('\n'),'',sprintf('\n'),'initValues(18.86200, 314, 0,1);',sprintf('\n'),'Niquist;']);
setParent(rptgen_cml_eval1,rptgen_lo_clo_for1);
 
% Create rptgen.cfr_text
rptgen_cfr_text2 = rptgen.cfr_text('isLiteral',true,...
'Content',['G (opel loop)  eigenvalues: ',sprintf('\n'),'%<A_eig>',sprintf('\n'),'',sprintf('\n'),'1/s G (closed loop )eigenvalues:',sprintf('\n'),'%<close_loop_eig>']);
setParent(rptgen_cfr_text2,rptgen_lo_clo_for1);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap1 = rptgen_hg.chg_fig_snap('PrintSize',[10 10],...
'isResizeFigure','manual',...
'MaxViewportSize',[7 9]);
setParent(rptgen_hg_chg_fig_snap1,rptgen_lo_clo_for1);
 
% Create rptgen.cfr_text
rptgen_cfr_text3 = rptgen.cfr_text('isLiteral',true,...
'Content',['Tm = %<Tm>',sprintf('\n'),'W0 = %<w0>']);
setParent(rptgen_cfr_text3,rptgen_lo_clo_for1);
 
