function [dx] = modelDynamics(t,x)
global Ls J Dp mif Rs Pm V wg Tm

% dx = InfBusTmVarDynamics(...
%     x(1), x(2), x(3), x(4),...
%     Ls, J, Dp, mif, Rs, Pm,V,wg);

dx = InfBusTmConstDynamics(...
    x(1), x(2), x(3), x(4),...
    Ls, J, Dp, mif, Rs, Tm ,V,wg);