function [] = displayParameters(Ltot,J,Dp,mif,Rl,Rtot,Tm)
 display(sprintf('Parameters:\n\tLtot = %f\n\tJ = %f\n\tRtot = %f\n\tDp = %f\n\tmif = %f\n\tRl = %f\n\tTm = %f\n',...
    Ltot,J,Rtot,Dp,mif,Rl,Tm));