function [F_dynamic_] = eSymbolicDynamics(...
    e1, e2, e3, e4,...
    x1,x2,x3,...
    Ltot_, J_, Dp_, mif_, Rl_, Rtot_)
e = [e1; e2; e3; e4];
d_ = e4;
A_ = [-Rtot_+Rl_*cos(d_) (Ltot_/2)*x3         -(Ltot_/2)*x2       0;...
       -(Ltot_/2)*x3_      -Rtot_+Rl_*cos(d_)  (Ltot_/2)*x1_-mif_  0;...
         0                 mif                  -Dp_                0;...
         0                 0                    -1                 0];

lambda_ = [Ltot_ 0 0 0; 0 Ltot_ 0 0;0 0 J_ 0;0 0 0 1];

B_ = [Rl*sin(d_)*x2;-Rl*sin(d_)*x1;0;0];
F_dynamic_ = lambda_^-1*(A*e_ + B_);